### PR TITLE
Adding a way to see Security Group Rules

### PR DESCRIPTION
**Pull request by asifhuawei**
Before Change :  Non-admin users were not able to see Security Group Rules applied to their spaces
After Change : Non-admin users can see the Security Group Rules for their spaces by using  cf space spaceName  --security-group-rules command

Issue : http://rnd-github.huawei.com/cloudfoundry/cli/issues/9

### CODE REVIEW

**Comment by shashidharatd** [comment]
Hi @asifhuawei 
1. The commit message is not complete. should have been something like " Adding a way to see Security Group Rules **by non admins**"
2. Does the change work for non-admins? Can you just add the output log from the command.
3. The PM of cli mentions in the story that you need to take care of both the commands `cf space` and `cf app` . But i can see only changes in spaces.

**Comment by shashidharatd** [comment]
The PR does not include test cases. Ideally any PR which is on enhancement type should include test cases for it to be accepted.

**Comment by asifhuawei** [comment]
Hi @shashidharatd 

Below are the updates on the review comments

1. The commit message is not complete. should have been something like " Adding a way to see Security Group Rules by non admins"  -- ***done***
2. Does the change work for non-admins? Can you just add the output log from the command. -- ***output given below in a comment***
3. The PM of cli mentions in the story that you need to take care of both the commands cf space and cf app . But i can see only changes in spaces.  -- ***as per discussion with @SrinivasChilveri and reviewing story 77733680 we came to the conclusion that pm wants to implement the changes either in space or app command and he also suggested that impelementing in space is better as in app command we dont have information of space guid and if we try to implement it in app command then we need to make one more call to CC***
4. These are undesired characters. the patch should not include these. similar for other files -- ***fixed***
5. The PR does not include test cases. Ideally any PR which is on enhancement type should include test cases for it to be accepted. -- ***New test case added for this feature. Result for the test case is given below in comments***

**Comment by asifhuawei** [comment]
**Non-admin user output**

cf@cf3:~$ cf org-users huawei
Getting users in org huawei as admin...

ORG MANAGER
  asif

BILLING MANAGER

ORG AUDITOR
cf@cf3:~$ cf login
API endpoint: https://api.10.244.0.34.xip.io

Email> asif

Password>
Authenticating...
OK

Targeted org huawei

Select a space (or press enter to skip):
1. apps
2. myspace

Space> 1
Targeted space apps



API endpoint:   https://api.10.244.0.34.xip.io (API version: 2.18.0)
User:           asif
Org:            huawei
Space:          apps
cf@cf3:~$ ./cf space apps --security-group-rules
Getting info for space apps in org huawei as asif...
OK

apps
       Org:               huawei
       Apps:
       Domains:           10.244.0.34.xip.io
       Services:
       Security Groups:   public_networks, dns
       Space Quota:

Getting rules for the security group  : public_networks...

   destination   :   0.0.0.0-9.255.255.255
   protocol      :   all

   destination   :   11.0.0.0-169.253.255.255
   protocol      :   all

   destination   :   169.255.0.0-172.15.255.255
   protocol      :   all

   destination   :   172.32.0.0-192.167.255.255
   protocol      :   all

   destination   :   192.169.0.0-255.255.255.255
   protocol      :   all

Getting rules for the security group  : dns...

   destination   :   0.0.0.0/0
   ports         :   53
   protocol      :   tcp

   destination   :   0.0.0.0/0
   ports         :   53
   protocol      :   udp

**Comment by asifhuawei** [comment]
**Test Case Output**

------------------------------
space command when logged in and an org is targeted when the security-group-rules flag is passed
  it shows space information and security group rules
  /home/cf/asif/.go/src/github.com/cloudfoundry/cli/cf/commands/space/space_test.go:122
â€¢***
------------------------------

**Comment by shashidharatd** [comment]
Hi @asifhuawei,
  One more clarification. The story has nothing to do with whether the user is admin or not. so can you plz take care of this aspect in commit message.
Commit message can be made little more meaningful.

Thanks
@shashidharatd

**Comment by asifhuawei** [comment]
@shashidharatd , the commit message is fixed as per review comments

**Pull request merged**
